language: c # or other C/C++ variants

# https://docs.travis-ci.com/user/caching/#ccache-cache
cache:
  ccache: true
  directories:
    - rocksdb-5.14.2

install:
  - git clone https://github.com/status-im/nim.git
  - cd nim
  - sh build_all.sh
  - cd ..
  - export PATH=$PWD/nim/bin:$PATH

script:
  - nimble install -dy && nimble test

matrix:
  # allow_failures:
  #   - os: osx

  include:
    - os: linux
      sudo: required
      before_install:
        - sudo apt-get install -y libssl-dev libgflags-dev libsnappy-dev
        - "[ -f rocksdb-5.14.2/Makefile ] || { wget https://github.com/facebook/rocksdb/archive/v5.14.2.tar.gz && tar xvf v5.14.2.tar.gz; }"
        # rocksdb not present on trusty - on a newer ubuntu you can apt-get install -y librocksdb-dev
        - cd rocksdb-5.14.2 && make shared_lib -j$(nproc) && sudo make INSTALL_PATH=/usr install-shared && cd ..

    - os: osx
      before_install:
        - brew update
        - brew install rocksdb ccache
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
        # - brew install gcc
