language: c

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - rocksdbCache
    - vendor/nimbus-build-system/vendor/Nim/bin

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10
  # disable LFS file downloading during regular cloning
  lfs_skip_smudge: true

matrix:
  include:
    - os: linux
      arch: amd64
      sudo: required
      env:
        - NPROC=2
      before_install:
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    - os: linux
      arch: arm64
      sudo: required
      env:
        - NPROC=6 # Worth trying more than 2 parallel jobs: https://travis-ci.community/t/no-cache-support-on-arm64/5416/8
        # (also used to get a different cache key than the amd64 one)
      before_install:
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
        - sudo apt-get install -y libpcre3-dev
    - os: osx
      env:
        - NPROC=2
      before_install:
        - launchctl setenv LIBRARY_PATH /usr/local/lib # for RocksDB

install:
  # build our own rocksdb to test with a fixed version that we think works
  - vendor/nimbus-build-system/scripts/build_rocksdb.sh rocksdbCache

script:
  - set -e # fail fast
  - make -j${NPROC} NIMFLAGS="--parallelBuild:${NPROC}" update # to allow a newer Nim version to be detected
  - make -j${NPROC} NIMFLAGS="--parallelBuild:${NPROC}"
  - build/nimbus --help
  - make -j${NPROC} NIMFLAGS="--parallelBuild:${NPROC}" test test-reproducibility

