language: c # or other C/C++ variants

cache: ccache

matrix:
  # allow_failures:
  #   - os: osx

  include:
    - os: linux
      cache: ccache
      sudo: required
      before_install:
        - sudo apt-get install -y libssl-dev librocksdb-dev
        - git clone https://github.com/status-im/nim.git
        - cd nim
        - sh build_all.sh
        - cd ..
        - export PATH=$PWD/nim/bin:$PATH
      script:
        - nimble install -dy && nimble test

    - os: osx
      before_install:
        - brew update
        - brew install rocksdb ccache
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
        # - brew install gcc

        - git clone https://github.com/status-im/nim.git
        - cd nim
        - sh build_all.sh
        - cd ..
        - export PATH=$PWD/nim/bin:$PATH


      script:
        - nimble install -dy && nimble test
