language: c

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - rocksdbCache
    - vendor/nimbus-build-system/vendor/Nim/bin

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10
  # disable LFS file downloading during regular cloning
  lfs_skip_smudge: true

matrix:
  include:
    - os: linux
      sudo: required
      before_install:
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    - os: osx
      before_install:
        - launchctl setenv LIBRARY_PATH /usr/local/lib # for RocksDB

install:
  # build our own rocksdb to test with a fixed version that we think works
  - vendor/nimbus-build-system/scripts/build_rocksdb.sh rocksdbCache

script:
  - set -e # fail fast
  - make -j2
  - build/nimbus --help
  - make -j2 test test-reproducibility

